### ISSUE TITLE
Not picking up variables from config/craft3-bugsnag.php

### ISSUE THREAD

**Issue by mikestecker** [pinfirestudios/craft3-bugsnag#3]
The config settings aren't being picked up from the config php file.

**Comment by jcherniak** [comment]
You sure?  We are using one now and it works great.  Did you copy it to PROJECT_ROOT/config/craft3-bugsnag.php?

**Comment by mikestecker** [comment]
Positive. Here's a screenshot:
<img width="1265" alt="screenshot 2017-11-03 13 19 42" src="https://user-images.githubusercontent.com/407465/32394262-bfca533e-c099-11e7-9555-737d12105bfa.png">

I'm using Andrew's multi-environment config which is why you see `CRAFTENV_BUGSNAG_API_KEY` instead of `BUGSNAG_API_KEY` in the screenshot. But I even tried replacing that with the key directly and it's not picking it up. Not a huge deal for me because I ended up manually putting it in through the settings field inside of Craft but I wanted to make you aware.

Also, you can see in the screenshot the two stages, however in the settings GUI, I only see 1: 
![screenshot 2017-11-03 13 27 29](https://user-images.githubusercontent.com/407465/32394565-c5b73e96-c09a-11e7-81f2-6cafcbf7b05c.png)

**Comment by jcherniak** [comment]
Yah...I renamed the fields to remove the Bugsnag prefix.  I did that in my project's config, not in the example one however.  I'll fix it.  Thanks for the report

**Comment by mikestecker** [comment]
Makes sense. I removed the prefix and it's working now, except `notifyReleaseStages` doesn't like the array, so I've commented out for now.
